const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {openRuntime}=require('./runtime.cjs');
const root=path.resolve(__dirname,'..'),balanceRoot=process.env.EMBERWILD_BALANCE_ROOT||path.resolve(root,'../Emberwild-Balance');
const model=require('../js/character/companion-model.js'),progression=require('../js/balance/progression-model.js');
test('Shared rating budgets include distributed points, actual rounding and level stairs',()=>{
 const classes=progression.defaults.classes,settings=progression.defaults.settings,c=model.defaults(classes,settings),d={...model.defaultPlans[0],rating:'D'},sss={...d,id:1050,rating:'SSS',growthPerLevel:{hp:2,atk:3,def:0}};
 const a=model.totals(d,classes,settings,c.ratings.weights),b=model.totals(sss,classes,settings,c.ratings.weights);assert(b.effectiveGrowth.atk>a.effectiveGrowth.atk);assert(b.effectiveGrowth.hp<a.effectiveGrowth.hp);assert.equal(c.activeLimit,6);assert.equal(c.ratings.maxGrowthGapPercent,13);assert.equal(c.ratings.maxBaseGapPercent,18);
 const extreme={...sss,growthPerLevel:{hp:100,atk:100,def:100}},warnings=model.warnings([d,extreme],classes,settings,c);assert(warnings.some(x=>x.id===1050&&x.message.includes('差距')));assert(warnings.some(x=>x.id===1050&&x.message.includes('SSS')));assert.equal(extreme.growthPerLevel.atk,100);
 assert.deepEqual(model.definition({...d,growthSteps:[]},classes,settings).growthSteps,[]);
 const custom=structuredClone(settings);custom.progression.starting={abilityPoints:1};custom.progression.levelRewards={abilityPoints:1};custom.progression.statsPerPoint={hp:3,attack:1,defense:1};const fractional={...d,initialStats:{hp:18.4},growthPerLevel:{hp:2.1},growthSteps:[],points:[0,1,2]},def=model.definition(fractional,classes,custom),first=progression.naturalStats(def,1),last=progression.naturalStats(def,60),actual=model.totals(fractional,classes,custom,c.ratings.weights);assert.equal(actual.baseStats.hp,first.hp);assert.equal(actual.effectiveGrowth.hp,(last.hp-first.hp+60)/59);
});
test('Full game: acquired roster, enlistment, UID ownership, equipment UI and persistence',async t=>{
 const game=await openRuntime(root),page=game.page;
 try{
  await page.evaluate(()=>{selectSaveSlot(1);start(0);});await page.waitForTimeout(30);
  await page.evaluate(()=>{clearInterval(timer);closeModal();globalThis.__rosterDefaults=exportableBalance();globalThis.__rosterReset=()=>{closeModal();applyBalanceConfig(structuredClone(__rosterDefaults),{persist:false});start(0);for(const id of [10,11,12,13,14]){closeModal();recruitCompanion(id);}closeModal();};globalThis.__rosterPersonal=h=>{const p=packParty().members.find(x=>memberKey(x)===memberKey(h)),out={...p};for(const key of ['bag','gold','ore','dust','gems','materials','consumables','potions'])delete out[key];return structuredClone(out);};globalThis.__rosterOwnership=()=>{const doc=packParty(),ids=doc.members.flatMap(h=>h.bag.map(g=>g.id)),worn=doc.members.flatMap(h=>h.equipped.filter(Boolean));return {ids,worn,uniqueItems:new Set(ids).size,uniqueWorn:new Set(worn).size};};});
  await t.test('New game creates only acquired people in the roster',async()=>{const r=await page.evaluate(()=>({count:party.members.length,enlisted:party.enlisted,active:party.active,html:partnerRosterView()}));assert.equal(r.count,1);assert.deepEqual(r.enlisted,[0]);assert.deepEqual(r.active,[0]);assert.doesNotMatch(r.html,/尚未招募|尚未取得/);});
  await t.test('Legacy six-member saves default all acquired heroes to enlisted',async()=>{const r=await page.evaluate(()=>{__rosterReset();const raw=structuredClone(packParty());delete raw.enlisted;for(const p of Object.values(raw.companionProfiles))delete p.rating;loadParty(raw);return {keys:party.members.map(memberKey),enlisted:party.enlisted,active:party.active,ratings:party.members.map(partnerRating)};});assert.deepEqual(r.keys,[0,10,11,12,13,14]);assert.deepEqual(r.enlisted,r.keys);assert.deepEqual(r.active,[0,10,11]);assert.deepEqual(r.ratings,[null,...Array(5).fill('D')]);});
  await t.test('Archive and reenlist preserve every personal field and equipped UID',async()=>{const r=await page.evaluate(()=>{__rosterReset();const h=partyMember(14);h.lv=20;__EMBERWILD_COMPANION_TEST_API.applyPlan(h,{fullHealth:true});h.xp=37;h.name='改名的弓手';h.mastery.archer=45;h.active.reverse();h.procSlots.reverse();h.supportSlots.reverse();const before=__rosterPersonal(h),ownership=__rosterOwnership(),archived=setPartnerEnlisted(14,false),stored=__rosterPersonal(h),back=setPartnerEnlisted(14,true);return {before,ownership,archived,stored,back,after:__rosterPersonal(h),afterOwnership:__rosterOwnership()};});assert(r.archived);assert(r.back);assert.deepEqual(r.stored,r.before);assert.deepEqual(r.after,r.before);assert.deepEqual(r.afterOwnership,r.ownership);});
  await t.test('Active heroes cannot leave enlistment; roster heroes cannot join combat directly',async()=>{const r=await page.evaluate(()=>{__rosterReset();const before=party.active.slice(),blocked=setPartnerEnlisted(10,false);setPartnerEnlisted(14,false);toggleMember(14);return {blocked,before,active:party.active,enlisted:party.enlisted};});assert.equal(r.blocked,false);assert.deepEqual(r.active,r.before);assert(!r.enlisted.includes(14));});
  await t.test('Dynamic ID acquisition reaches roster at capacity and can later join combat',async()=>{const r=await page.evaluate(()=>{__rosterReset();const d=exportableBalance();d.companions.push({...d.companions[0],id:1042,names:['動態夥伴'],rating:'A'});applyBalanceConfig(d);closeModal();acquireCompanion(1042);closeModal();const before=party.enlisted.slice(),blocked=setPartnerEnlisted(1042,true),message=$('toast').textContent;setPartnerEnlisted(14,false);const admitted=setPartnerEnlisted(1042,true);toggleMember(1042);return {before,blocked,message,admitted,ids:party.members.map(memberKey),rating:partnerRating(partyMember(1042)),dialog:$('modal').textContent};});assert.equal(r.before.length,6);assert.equal(r.blocked,false);assert.match(r.message,/現役夥伴已達上限/);assert(r.admitted);assert.equal(r.ids.length,7);assert.equal(r.rating,'A');assert.match(r.dialog,/替換出戰/);});
  await t.test('Single editable limit never silently evicts existing enlisted heroes',async()=>{const r=await page.evaluate(()=>{closeModal();const d=exportableBalance();d.companionSettings.activeLimit=8;applyBalanceConfig(d);setPartnerEnlisted(14,true);const before=party.enlisted.slice();d.companionSettings.activeLimit=3;applyBalanceConfig(d);save();loadParty(JSON.parse(localStorage.getItem(KEY)));return {before,after:party.enlisted,limit:__EMBERWILD_COMPANION_TEST_API.config.activeLimit};});assert.equal(r.before.length,7);assert.deepEqual(r.after,r.before);assert.equal(r.limit,3);});
  await t.test('Archived people stay out of combat selectors and retain access to their single token',async()=>{const r=await page.evaluate(()=>{__rosterReset();const h=partyMember(14);h.name='名冊隱藏角色';setPartnerEnlisted(14,false);setTab('roster');const team=document.querySelector('.roster-list').textContent;setTab('character');const character=[...document.querySelectorAll('.companion-character-card')].map(x=>x.textContent).join('');return {roster:partnerRosterView(),team,skills:skillsView(),character,worn:wornEquipmentView(),ordinary:h.equipped};});assert.match(r.roster,/名冊隱藏角色/);for(const k of ['team','skills','character'])assert.doesNotMatch(r[k],/名冊隱藏角色/);assert.match(r.worn,/showCompanionTokens\(14\)/);assert(r.ordinary.every(x=>x===null));});
  await t.test('Ordinary equipment lists the player and each acquired companion has one token slot',async()=>{const r=await page.evaluate(()=>{partyMember(0).name='TEST1';setPartnerEnlisted(14,true);party.active=[12,14,13];setTab('worn');return {players:[...document.querySelectorAll('.worn-character-item')].map(el=>({id:Number(el.dataset.memberKey),text:el.textContent})),tokens:[...document.querySelectorAll('[data-token-owner]')].map(el=>Number(el.dataset.tokenOwner))};});assert.deepEqual(r.players.map(x=>x.id),[0]);assert.match(r.players[0].text,/TEST1.*後備.*戰士/);assert.deepEqual(r.tokens,[10,11,12,13,14]);});
  await t.test('Candidates filter wrong jobs, positions, levels, drafts and all worn gear',async()=>{const r=await page.evaluate(()=>{__rosterReset();const good=gear(1,0,0,0),job=gear(1,0,0,1),slot=gear(1,1,0,0),high=gear(10,0,0,0),draft=gear(1,0,0,0);state.bag.push(good,job,slot,high,draft);inlineAffixDrafts.set(affixDraftKey(draft),[]);setTab('worn');selectWornSlot(0,0);return {ids:[...document.querySelectorAll('.worn-candidate')].map(el=>el.dataset.gearId),good:good.id,bad:[job.id,slot.id,high.id,draft.id,...party.members.flatMap(h=>h.equipped.filter(Boolean))]};});assert(r.ids.includes(r.good));for(const id of r.bad)assert(!r.ids.includes(id));});
  await t.test('Empty slot equips via original UID operation without copying',async()=>{const r=await page.evaluate(()=>{closeModal();const h=partyMember(0);unequipSharedGear(h.equipped[0]);const g=state.bag.find(g=>g.slot===0&&!gearWearer(g.id)&&gearWearableJobs(g).includes(0));selectWornSlot(0,0);previewEquip(g.id,0,0);return {current:h.equipped[0],id:g.id,owner:memberKey(gearWearer(g.id)),o:__rosterOwnership()};});assert.equal(r.current,r.id);assert.equal(r.owner,0);assert.equal(r.o.ids.length,r.o.uniqueItems);assert.equal(r.o.worn.length,r.o.uniqueWorn);});
  await t.test('Replacement compares final stats and existing base, affix and enhancement details',async()=>{const r=await page.evaluate(()=>{const h=partyMember(0),g=gear(1,0,2,0);g.plus=3;g.affix=[{type:0,rank:2,value:4}];g.prefixId='keen';g.suffixId='fury';state.bag.push(g);const old=h.equipped[0],before=stats(h),rows=equipmentComparison(h,g,0);previewEquip(g.id,0,0);const html=$('modal').innerHTML,unchanged=h.equipped[0]===old;confirmEquipComparison(g.id,0,0);return {old,newId:g.id,current:h.equipped[0],oldWorn:!!gearWearer(old),once:state.bag.filter(x=>x.id===old).length,before,after:stats(h),rows,html,unchanged};});assert(r.unchanged);assert.equal(r.current,r.newId);assert.equal(r.oldWorn,false);assert.equal(r.once,1);for(const re of [/目前穿戴/,/準備穿戴/,/基底評級/,/前綴|銳眼/,/強化|\+3/])assert.match(r.html,re);const a=r.rows.find(x=>x.label==='攻擊力');assert.equal(a.before,r.before.atk);assert.equal(a.after,r.after.atk);});
  await t.test('Unequip keeps identical object and item count',async()=>{const r=await page.evaluate(()=>{const h=partyMember(0),id=h.equipped[0],ref=findGear(id),count=state.bag.length;unequipSharedGear(id);return {slot:h.equipped[0],worn:!!gearWearer(id),same:findGear(id)===ref,count,after:state.bag.length};});assert.equal(r.slot,null);assert.equal(r.worn,false);assert(r.same);assert.equal(r.count,r.after);});
  await t.test('Core ordinary equip rejects wrong jobs, levels, positions and token items',async()=>{const r=await page.evaluate(()=>{const h=partyMember(0),before=h.equipped.slice(),job=gear(1,0,0,1),armor=gear(1,1,0,0),high=gear(10,0,0,0),token=__EMBERWILD_TOKEN_TEST.makeToken('arcane');state.bag.push(job,armor,high,token);equipCompanionToken(token.id,10);for(const [id,pos] of [[job.id,0],[armor.id,0],[high.id,0],[token.id,0]]){equipSharedGear(id,0,pos);previewEquip(id,0,pos);}return {before,after:h.equipped,owner:memberKey(gearWearer(token.id)),open:$('modal').open};});assert.deepEqual(r.after,r.before);assert.equal(r.owner,10);assert.equal(r.open,false);});
  await t.test('Real UI clicks select player and slot, equip, compare, replace and unload',async()=>{const ids=await page.evaluate(()=>{__rosterReset();const h=partyMember(0);unequipSharedGear(h.equipped[0]);const a=gear(1,0,0,0),b=gear(1,0,1,0);state.bag.push(a,b);setTab('worn');return [a.id,b.id];});await page.waitForTimeout(30);await page.evaluate(()=>closeModal());await page.locator('.worn-character-item[data-member-key="0"]').click();await page.locator('[data-equip-position="0"]').click();await page.locator('.worn-candidate[data-gear-id="'+ids[0]+'"]').click();assert.equal(await page.evaluate(()=>partyMember(0).equipped[0]),ids[0]);await page.locator('.worn-candidate[data-gear-id="'+ids[1]+'"]').click();assert.equal(await page.evaluate(()=>partyMember(0).equipped[0]),ids[0]);await page.locator('#modal button').filter({hasText:'確認穿戴'}).click();assert.equal(await page.evaluate(()=>partyMember(0).equipped[0]),ids[1]);assert(await page.locator('.worn-candidate[data-gear-id="'+ids[0]+'"]').count());await page.locator('.worn-slot').first().getByRole('button',{name:'卸下',exact:true}).click();assert.equal(await page.evaluate(()=>partyMember(0).equipped[0]),null);});
  await t.test('Locked and worn salvage protections preserve original inventory ownership',async()=>{const r=await page.evaluate(()=>{__rosterReset();setPartnerEnlisted(14,false);const token=__EMBERWILD_TOKEN_TEST.makeToken('arcane'),g=gear(1,0,0,0);state.bag.push(g,token);equipCompanionToken(token.id,14);const worn=token.id;toggleGearLock(g.id);salvage(g.id);const locked=!!findGear(g.id);salvage(worn);const retained=!!findGear(worn);toggleGearLock(g.id);salvage(g.id);return {locked,retained,salvaged:!findGear(g.id),o:__rosterOwnership()};});assert(r.locked);assert(r.retained);assert(r.salvaged);assert.equal(r.o.ids.length,r.o.uniqueItems);});
  await t.test('Removed definitions retain acquired profiles, remove old offers and cannot duplicate recruitment',async()=>{const r=await page.evaluate(()=>{__rosterReset();const personal=party.members.map(__rosterPersonal),o=__rosterOwnership();acquireCompanion(10);const duplicate=__rosterOwnership(),cfg=exportableBalance();cfg.companions=[];applyBalanceConfig(cfg);save();loadParty(JSON.parse(localStorage.getItem(KEY)));showCompanionRecruitment();return {personal,after:party.members.map(__rosterPersonal),o,duplicate,afterO:__rosterOwnership(),dialog:$('modal').textContent,profiles:Object.keys(party.companionProfiles)};});assert.deepEqual(r.after,r.personal);assert.deepEqual(r.duplicate,r.o);assert.deepEqual(r.afterO,r.o);assert.match(r.dialog,/目前沒有可招募的夥伴/);assert.equal(r.profiles.length,5);});
  await t.test('Browser reload restores exact roster, enlistment, combat, growth, skills, names and all equipped UIDs',async()=>{const before=await page.evaluate(()=>{closeModal();setPartnerEnlisted(14,false);partyMember(14).name='持久名冊角色';save();return {enlisted:party.enlisted,active:party.active,personal:party.members.map(__rosterPersonal),o:__rosterOwnership()};});await page.reload();await page.evaluate(()=>{continueFromTitle();closeModal();clearInterval(timer);});const after=await page.evaluate(()=>{const d=packParty(),ids=d.members.flatMap(h=>h.bag.map(g=>g.id)),worn=d.members.flatMap(h=>h.equipped.filter(Boolean));return {enlisted:party.enlisted,active:party.active,personal:d.members.map(p=>{const a={...p};for(const k of ['bag','gold','ore','dust','gems','materials','consumables','potions'])delete a[k];return a;}),o:{ids,worn,uniqueItems:new Set(ids).size,uniqueWorn:new Set(worn).size}};});assert.deepEqual(after,before);});
  await t.test('Malformed enlistment rejects atomically without replacing current party',async()=>{const r=await page.evaluate(()=>{const raw=structuredClone(packParty()),live=party;let rejected=0;for(const enlisted of [null,{},[],[0,0],[99999],[0]])try{loadParty({...raw,enlisted});}catch{rejected++;}return {rejected,same:party===live};});assert.equal(r.rejected,6);assert(r.same);});
  assert.deepEqual(game.errors,[]);
 }finally{await game.browser.close();}
});
test('Editor and runtime share ratings, dynamic definitions, exclusive skills and soft warnings',async t=>{
 const game=await openRuntime(root),editor=await openRuntime(balanceRoot,'balance-editor.html');
 try{
  await game.page.evaluate(()=>{selectSaveSlot(1);start(0);});await game.page.waitForTimeout(30);await game.page.evaluate(()=>{clearInterval(timer);closeModal();});const defaults=await game.page.evaluate(()=>exportableBalance());
  await t.test('Both applications contain exactly the same shared model and effective limits',async()=>{const html=fs.readFileSync(path.join(balanceRoot,'balance-editor.html'),'utf8'),embedded=html.split('<script id="companion-model-v1">\n')[1].split('\n</script>')[0];assert.equal(embedded,fs.readFileSync(path.join(root,'js/character/companion-model.js'),'utf8'));const r=await editor.page.evaluate(()=>({cfg:__EMBERWILD_MASTERY_EDITOR.cleanExport(),issues:validateData()}));assert.deepEqual(r.issues,[]);assert.deepEqual(r.cfg.companionSettings,defaults.companionSettings);});
  await t.test('Seven grades survive balance and save round trips regardless of level, name or equipment',async()=>{const r=await game.page.evaluate(()=>{const d=exportableBalance();d.companions=EmberwildCompanions.ratings.map((rating,i)=>({...d.companions[0],id:1000+i,names:['評級夥伴'+i],rating}));applyBalanceConfig(d);for(const p of d.companions){closeModal();acquireCompanion(p.id);}closeModal();const before=party.members.slice(1).map(partnerRating);for(const h of party.members.slice(1)){h.lv=20;h.name='自訂 '+h.companionId;h.equipped=[null,null,null,null,null];}save();loadParty(JSON.parse(localStorage.getItem(KEY)));return {before,after:party.members.slice(1).map(partnerRating),exported:exportableBalance().companions.map(p=>p.rating),html:partnerRosterView(),detail:characterView()};});assert.deepEqual(r.before,model.ratings);assert.deepEqual(r.after,model.ratings);assert.deepEqual(r.exported,model.ratings);assert.match(r.html,/SSS/);assert.match(r.detail,/評級/);});
  await t.test('Actual companion controls edit grade, independent base and growth with warnings',async()=>{await editor.page.evaluate(()=>{currentSection='companions';render();});await editor.page.locator('#companionRating').selectOption('SSS');for(const [f,v] of [['initialStats','19'],['growthPerLevel','8']]){await editor.page.locator('[data-partner-override="'+f+'"]').check();const field=editor.page.locator('[data-partner-stat="'+f+'"][data-stat-key="atk"]');await field.fill(v);await field.dispatchEvent('change');}const r=await editor.page.evaluate(()=>({p:data.companions[0],issues:validateData(),warnings:companionBalanceWarnings(),cfg:__EMBERWILD_MASTERY_EDITOR.cleanExport()}));assert.equal(r.p.rating,'SSS');assert.equal(r.p.initialStats.atk,19);assert.equal(r.p.growthPerLevel.atk,8);assert.deepEqual(r.issues,[]);assert(r.warnings.length>0);assert.equal(r.cfg.companions[0].growthPerLevel.atk,8);});
  await t.test('Soft warnings allow actual release download without rewriting values or approval dialogs',async()=>{let count=0;editor.page.on('dialog',async d=>{count++;await d.accept();});const p=editor.page.waitForEvent('download');await editor.page.locator('#releaseBtn').click();const dl=await p;assert(dl.suggestedFilename().includes('release'));assert.equal(count,0);assert.equal(await editor.page.evaluate(()=>data.companions[0].growthPerLevel.atk),8);});
  await t.test('Balance inputs and dynamic skill target options export into the real game',async()=>{await editor.page.evaluate(()=>{currentSection='companionBalance';render();});for(const [key,v] of [['activeLimit','10'],['ratings.maxGrowthGapPercent','11'],['ratings.ranges.SSS.growth.max','8']]){const el=editor.page.locator('[data-partner-setting="'+key+'"]');await el.fill(v);await el.dispatchEvent('change');}await editor.page.evaluate(()=>{currentSection='companions';render();});await editor.page.locator('#addCompanion').click();const id=await editor.page.evaluate(()=>data.companions.at(-1).id);await editor.page.locator('#companionRating').selectOption('A');await editor.page.evaluate(()=>{currentSection='skills';selected.skillClass=0;selected.skillTab='active';selected.skill=0;render();});assert(await editor.page.locator('#skillPartnerId option[value="'+id+'"]').count());await editor.page.locator('#skillPartnerId').selectOption(String(id));const doc=await editor.page.evaluate(()=>__EMBERWILD_MASTERY_EDITOR.cleanExport());const r=await game.page.evaluate(({doc,id})=>{closeModal();applyBalanceConfig(doc);start(0);recruitCompanion(id);closeModal();return {cfg:__EMBERWILD_COMPANION_TEST_API.config,grade:partnerRating(partyMember(id)),allowed:coreSkillAvailableToHero(0,0,partyMember(id)),learned:partyMember(id).skills[0],ids:party.members.map(memberKey)};},{doc,id});assert.equal(r.cfg.activeLimit,10);assert.equal(r.cfg.ratings.maxGrowthGapPercent,11);assert.equal(r.cfg.ratings.ranges.SSS.growth.max,8);assert.equal(r.grade,'A');assert(r.allowed);assert.equal(r.learned,1);assert(r.ids.includes(id));});
  await t.test('Independent initial and growth values reach existing final HP, attack, defense and speed formulas',async()=>{const r=await game.page.evaluate(()=>{const d=exportableBalance(),p=d.companions[0];p.initialStats={hp:18,atk:19,def:1,crit:.04,critDamage:1.5,speed:120};p.growthPerLevel={hp:2,atk:4,def:0,crit:0,critDamage:0,speed:2};p.growthSteps=[];applyBalanceConfig(d);recruitCompanion(p.id);closeModal();const h=partyMember(p.id);h.equipped=[null,null,null,null,null];h.stats=[0,0,0];h.advanced=false;h.lv=1;const first=stats(h);h.lv=5;return {first,last:stats(h)};});assert.equal(r.first.hp,18);assert.equal(r.first.atk,19);assert.equal(r.first.def,1);assert.equal(r.last.hp,26);assert.equal(r.last.atk,35);assert.equal(r.last.def,1);assert.equal(r.last.speed-r.first.speed,8);});
  await t.test('Stable ID owners can use active, proc and support skills; other same-class heroes and monsters cannot',async()=>{const r=await game.page.evaluate(()=>{const d=exportableBalance();d.companions=structuredClone(EmberwildCompanions.defaultPlans);for(const sk of d.classes[0].skills)sk.partnerId=null;d.classes[0].skills[0].partnerId=10;d.classes[0].skills[0].usageScope='shared';d.classes[0].skills[2].partnerId=10;d.supportSkills[0][0].partnerId=10;applyBalanceConfig(d);start(0);state.lv=7;recruitCompanion(10);recruitCompanion(11);closeModal();const owner=partyMember(10),other=partyMember(11);owner.name='改名不改 ID';for(const h of [owner,other]){h.skills[0]=1;h.skills[2]=1;h.supportLevels[0]=1;h.active=[0,null];h.procSlots=[2,null];h.supportSlots=[0,null];}foes=[makeEnemy(0,owner,()=>.9)];foes[0].id='exclusive-test';const allowed=[owner,other].map(h=>({core:coreSkillAvailableToHero(0,0,h),proc:validProcIndex(h,2),support:__EMBERWILD_MASTERY.supportMissingRequirements(h,0,true)})),cast=castPartySkill(other,0,battleStats(other)),support=castSupport(other,0);withHero(other,()=>slotSupport(0,1));const slot=other.supportSlots[1],enemyCast=castEnemySharedSkill(foes[0],sharedSkillById('job0-core0')),ownerCast=castPartySkill(owner,0,battleStats(owner));save();return {allowed,cast,support,slot,enemyCast,ownerCast,partnerId:exportableBalance().classes[0].skills[0].partnerId};});assert(r.allowed[0].core);assert(r.allowed[0].proc);assert.deepEqual(r.allowed[0].support,[]);assert.equal(r.allowed[1].core,false);assert.equal(r.allowed[1].proc,false);assert(r.allowed[1].support.includes('指定夥伴專屬'));assert.equal(r.cast,false);assert.equal(r.support,false);assert.equal(r.slot,null);assert.equal(r.enemyCast,false);assert.notEqual(r.ownerCast,false);assert.equal(r.partnerId,10);});
  await t.test('Reload preserves exclusive relationships and names while clearing invalid nonowner slots',async()=>{await game.page.reload();await game.page.evaluate(()=>{continueFromTitle();clearInterval(timer);closeModal();});const r=await game.page.evaluate(()=>({name:partyMember(10).name,owner:coreSkillAvailableToHero(0,0,partyMember(10)),other:coreSkillAvailableToHero(0,0,partyMember(11)),meta:CLASSES[0].skills[0][6].partnerId,active:partyMember(11).active}));assert.equal(r.name,'改名不改 ID');assert(r.owner);assert.equal(r.other,false);assert.equal(r.meta,10);assert(!r.active.includes(0));});
  await t.test('Legacy JSON without grades and ownership restrictions retains generic skills and D fallback',async()=>{const r=await game.page.evaluate(d=>{for(const p of d.companions)delete p.rating;delete d.companionSettings;for(const c of d.classes)for(const sk of c.skills)delete sk.partnerId;for(const row of d.supportSkills)for(const sk of row)delete sk.partnerId;applyBalanceConfig(d);return {grades:exportableBalance().companions.map(p=>p.rating),generic:coreSkillAvailableToHero(0,0,partyMember(11)),limit:__EMBERWILD_COMPANION_TEST_API.config.activeLimit};},structuredClone(defaults));assert.deepEqual(r.grades,Array(5).fill('D'));assert(r.generic);assert.equal(r.limit,6);});
  await t.test('Thirty owned heroes scroll in roster while ordinary equipment lists one player and tokens remain available',async()=>{const r=await game.page.evaluate(()=>{const d=exportableBalance();d.companions=Array.from({length:29},(_,i)=>({...d.companions[0],id:2000+i,names:['大量夥伴'+i]}));applyBalanceConfig(d);start(0);for(const p of d.companions){closeModal();acquireCompanion(p.id);}closeModal();setTab('partnerRoster');const list=document.querySelector('.partner-owned-list'),count=list.children.length,scroll=document.querySelector('.companion-management-page').scrollHeight>document.querySelector('.companion-management-page').clientHeight;setTab('worn');return {owned:party.members.length,enlisted:party.enlisted.length,count,scroll,worn:document.querySelectorAll('.worn-character-item').length,ids:packParty().members.flatMap(h=>h.bag.map(g=>g.id))};});assert.equal(r.owned,30);assert.equal(r.count,30);assert.equal(r.enlisted,6);assert.equal(r.worn,1);assert(r.scroll);assert.equal(new Set(r.ids).size,r.ids.length);});
  await t.test('Backpack and modal retain management details without equipment-to-person buttons',async()=>{const r=await game.page.evaluate(()=>{setTab('equipment');const html=document.querySelector('main').innerHTML;showGearDetail(state.bag[0].id);return {html,modal:$('modal').innerHTML};});for(const html of [r.html,r.modal]){assert.doesNotMatch(html,/給[^<]*穿戴/);assert.doesNotMatch(html,/onclick="(?:previewEquip|equipFromDetail)\(/);}assert.match(r.html,/鎖定/);assert.match(r.html,/分解/);});
  assert.deepEqual(game.errors,[]);assert.deepEqual(editor.errors,[]);
 }finally{await game.browser.close();await editor.browser.close();}
});
