const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {loadRuntime}=require('./headless-runtime.cjs'),M=require('../js/items/companion-token-model.js');
const root=path.resolve(__dirname,'..');
function game(){const r=loadRuntime(root);r.run(`start(0);closeModal();for(const id of [10,11,12,13,14])recruitCompanion(id);closeModal();`);return r;}
function json(r,code){return JSON.parse(r.run(`JSON.stringify(${code})`));}
test('real runtime: five distinct internal growth profiles, decimals and zero growth; no ordinary gear sources',()=>{
 const r=game(),result=json(r,`(()=>{const player=stats(playerHero()),rows=[];for(const lv of [1,2,15,30,60]){playerHero().lv=lv;playerHero().won=lv>=30;syncParty();rows.push(party.members.slice(1).map(h=>({id:h.companionId,lv:h.lv,...stats(h)})));}const h=partyMember(10),before=stats(h),g=gear(12,0,3,0);g.plus=10;state.bag.push(g);h.equipped[0]=g.id;const after=stats(h);return {player,rows,before,after,weapon:__EMBERWILD_MASTERY.currentWeaponType(h),count:state.bag.length};})()`);
 assert.deepEqual(result.before,result.after);assert.equal(result.weapon,'sword');assert.equal(result.count,6);
 assert.deepEqual(result.rows.map(row=>row.map(h=>h.lv)),[1,2,15,30,60].map(lv=>Array(5).fill(lv)));
 assert.equal(result.rows[0][0].hp,47);assert.equal(result.rows[0][1].hp,51);assert.notEqual(result.rows[4][0].atk,result.rows[4][1].atk);assert.equal(result.rows[4][0].crit,result.rows[0][0].crit);
 const d=json(r,`exportableBalance().companions[0]`);assert.equal(d.growthPerLevel.hp,6.1);assert.equal(d.equipmentInternalized,1);assert.deepEqual(r.errors,[]);
});
test('single-slot eligibility, exclusive UID ownership, reserves, compound percentages, quality, enhancement, save/reload',()=>{
 const r=game(),out=json(r,`(()=>{const h=partyMember(10),other=partyMember(12),g=__EMBERWILD_TOKEN_TEST.makeToken('berserk',2),base=stats(h);state.bag.push(g);const player=equipCompanionToken(g.id,memberKey(playerHero())),first=equipCompanionToken(g.id,10),duplicate=equipCompanionToken(g.id,12);equipSharedGear(g.id,0,0);const equipped=stats(h);setPartnerEnlisted(14,false);unequipCompanionToken(10);const all=party.members.slice(1).map(x=>{const ok=equipCompanionToken(g.id,memberKey(x));unequipCompanionToken(memberKey(x));return ok;});equipCompanionToken(g.id,14);g.plus=4;const enhanced=stats(partyMember(14));const raw=packParty(),valid=validateParty(raw);loadParty(raw);const restored=partyMember(14).tokenId,ids=packParty().members.flatMap(x=>x.bag.map(g=>g.id));return {player,first,duplicate,base,equipped,all,enhanced,restored,id:g.id,ids,unique:new Set(ids).size,hero:playerHero().equipped};})()`);
 assert.equal(out.player,false);assert(out.first);assert.equal(out.duplicate,false);assert(out.all.every(Boolean));assert.equal(out.restored,out.id);assert.equal(out.ids.length,out.unique);assert(out.equipped.atk>out.base.atk);assert.equal(out.equipped.critDamage,1.5625);assert(!out.hero.includes(out.id));assert.deepEqual(r.errors,[]);
});
test('legacy migration keeps exact gear, player loadout and character data, is idempotent, preserves overflow in queued loot',()=>{
 const r=game(),out=json(r,`(()=>{const raw=packParty();delete raw.companionEquipmentVersion;raw.members[0].lv=1;const retained=[];for(const h of raw.members.slice(1)){const g=gear(1,0,1,h.job);g.plus=2;g.locked=true;g.affix=[{type:0,rank:1,value:2}];h.bag.push(g);h.equipped[0]=g.id;retained.push(structuredClone(g));}const hero=raw.members[0].equipped.slice();loadParty(raw);const first=packParty();loadParty(first);const second=packParty();const all=state.bag.map(g=>g.id),preserved=retained.every(g=>JSON.stringify(state.bag.find(x=>x.id===g.id))===JSON.stringify(g));const overflow=structuredClone(raw);while(overflow.members[0].bag.length<RULES.bagCapacity)overflow.members[0].bag.push(gear(1,0,0,0));loadParty(overflow);const q=pendingGearLoot.length,packed=packParty();loadParty(packed);return {preserved,hero,after:playerHero().equipped,cleared:first.members.slice(1).every(h=>h.equipped.every(x=>x===null)&&h.tokenId===null),all,unique:new Set(all).size,first:first.members.flatMap(h=>h.bag.map(g=>g.id)),second:second.members.flatMap(h=>h.bag.map(g=>g.id)),queued:q,reloadedQueued:pendingGearLoot.length,bag:state.bag.length,cap:RULES.bagCapacity};})()`);
 assert(out.preserved);assert(out.cleared);assert.deepEqual(out.after,out.hero);assert.equal(out.all.length,out.unique);assert.deepEqual(out.first,out.second);assert.equal(out.queued,5);assert.equal(out.reloadedQueued,5);assert.equal(out.bag,out.cap);
});
test('damaged token state and invalid configs reject before replacing the live party',()=>{
 const r=game(),out=json(r,`(()=>{const g=__EMBERWILD_TOKEN_TEST.makeToken('arcane');state.bag.push(g);equipCompanionToken(g.id,10);const raw=packParty(),live=party;let errors=0;for(const mutate of [d=>d.members[0].tokenId=g.id,d=>d.members[2].tokenId=g.id,d=>d.members[0].bag.find(x=>x.id===g.id).snapshot.ability.chance=2]){const d=structuredClone(raw);mutate(d);try{loadParty(d);}catch{errors++;}}return {errors,same:party===live};})()`);assert.equal(out.errors,3);assert(out.same);
 assert.throws(()=>M.normalize({...M.defaults,qualityMultipliers:[0,1,1,1]}));assert.throws(()=>M.validateAbility({...M.defaults.catalog[0].ability,event:'damage',action:'extraDamage'}));
});
test('independent loot keeps regular rules and RNG intact; weights, restrictions, boost, quality and overflow are live',()=>{
 const r=game(),out=json(r,`(()=>{const d=exportableBalance(),rules=JSON.stringify(d.balanceSettings.drops);d.companionTokens.drop.chanceByDifficulty=[1,1,1];d.companionTokens.drop.qualityWeights=[0,0,0,1];d.companionTokens.catalog=d.companionTokens.catalog.map(t=>({...t,drop:{...t.drop,weight:t.id==='arcane'?1:0}}));applyBalanceConfig(d);const e={id:'loot',lv:1,region:0,monsterId:'map0_mob0',kind:'normal',difficulty:0,maxDrops:99},drops=__EMBERWILD_TOKEN_TEST.rollTokens(e,()=>0),twice=__EMBERWILD_TOKEN_TEST.rollTokens(e,()=>0);const same=JSON.stringify(exportableBalance().balanceSettings.drops)===rules;const cfg=exportableBalance();cfg.companionTokens.drop.maps=[1];applyBalanceConfig(cfg);const restricted=__EMBERWILD_TOKEN_TEST.rollTokens({...e,id:'restricted',__tokenDropRolled:false},()=>0).length;cfg.companionTokens.drop.maps=[];applyBalanceConfig(cfg);while(state.bag.length<RULES.bagCapacity)state.bag.push(gear(1,0,0,0));const queued=__EMBERWILD_TOKEN_TEST.rollTokens({...e,id:'queued',__tokenDropRolled:false},()=>0);return {id:drops[0].tokenId,quality:drops[0].rar,twice:twice.length,same,restricted,queued:pendingGearLoot.some(g=>g.id===queued[0].id),boost:effectiveDropChance({chanceByDifficulty:[.01,.01,.01]},e,1)};})()`);assert.equal(out.id,'arcane');assert.equal(out.quality,3);assert.equal(out.twice,0);assert(out.same);assert.equal(out.restricted,0);assert(out.queued);assert.equal(out.boost,.02);
});
test('all ten real combat abilities, cooldown, probability, duration, protection and reset',()=>{
 const r=game();r.run(`globalThis.setupToken=(id,owner=10)=>{resetEncounter();playerHero().lv=15;syncParty();party.active=[0,owner];const h=partyMember(owner);h.hp=stats(h).hp;const g=__EMBERWILD_TOKEN_TEST.makeToken(id,0);state.bag.push(g);equipCompanionToken(g.id,owner);foes=[{id:'test-enemy',name:'測試怪物',hp:10000,maxhp:10000,def:0,atk:2,lv:1,element:'physical',race:'beast',kind:'normal',region:0,difficulty:0,turn:0}];partyClock=1;return h;};Math.random=()=>0;`);
 let out=json(r,`(()=>{const h=setupToken('berserk');foes[0].hp=1;performHeroBasic(h);return {attack:effectTotal(heroKey(h),'attack'),used:__EMBERWILD_TOKEN_TEST.combat.get(10).used};})()`);assert.equal(out.attack,.12);assert.equal(out.used,1);
 out=json(r,`(()=>{const h=setupToken('guardian');const before=h.hp;h.hp-=1;EmberwildTokenRuntime.afterDamage(h,foes[0],before,h.hp);const a=effectTotal(heroKey(h),'guard');h.hp-=1;EmberwildTokenRuntime.afterDamage(h,foes[0],before-1,h.hp);partyClock=3;return {a,expired:effectTotal(heroKey(h),'guard'),used:__EMBERWILD_TOKEN_TEST.combat.get(10).used};})()`);assert.equal(out.a,.1);assert.equal(out.expired,0);assert.equal(out.used,1);
 out=json(r,`(()=>{const h=setupToken('pursuit');h.procSlots=[null,null];const before=foes[0].hp;performHeroBasic(h);return {dealt:before-foes[0].hp,atk:stats(h).atk,used:__EMBERWILD_TOKEN_TEST.combat.get(10).used};})()`);assert(out.dealt>out.atk);assert.equal(out.used,1);
 out=json(r,`(()=>{const h=setupToken('arcane');const before=foes[0].hp;castPartySkill(h,0,battleStats(h));return {dealt:before-foes[0].hp,used:__EMBERWILD_TOKEN_TEST.combat.get(10).used};})()`);assert(out.dealt>0);assert.equal(out.used,1);
 out=json(r,`(()=>{const h=setupToken('echo');castPartySkill(h,0,battleStats(h));return effectTotal(heroKey(h),'power');})()`);assert.equal(out,.08);
 out=json(r,`(()=>{const h=setupToken('hunt');h.procSlots=[null,null];const hits=[];for(let n=0;n<3;n++){const hp=foes[0].hp;performHeroBasic(h);hits.push(hp-foes[0].hp);}return hits;})()`);assert(out[2]>out[0]);assert.equal(out[0],out[1]);
 out=json(r,`(()=>{const h=setupToken('prayer',13);h.skills[1]=1;h.hp=1;const before=h.hp;castPartySkill(h,1,battleStats(h));return {healed:h.hp-before,used:__EMBERWILD_TOKEN_TEST.combat.get(13).used};})()`);assert(out.healed>0);assert.equal(out.used,1);
 out=json(r,`(()=>{const h=setupToken('revival');const max=stats(h).hp;h.hp=max*.2;EmberwildTokenRuntime.afterDamage(h,foes[0],max,h.hp);const first=h.shield;h.shield=0;h.hp-=1;EmberwildTokenRuntime.afterDamage(h,foes[0],max*.2,h.hp);return {first,second:h.shield};})()`);assert(out.first>0);assert.equal(out.second,0);
 out=json(r,`(()=>{const h=setupToken('plunder');h.hp=1;resolveHit(foes[0],10,h,'physical',false);return h.hp;})()`);assert(out>1);
 out=json(r,`(()=>{const h=setupToken('endurance');__EMBERWILD_TOKEN_TEST.ensureBattle(h);partyClock=4;running=true;closeModal();const iterator=pacedRound();iterator.next();const attack=effectTotal(heroKey(h),'attack');iterator.return();resetEncounter();return {attack,cleared:__EMBERWILD_TOKEN_TEST.combat.size,effects:effectTotal(heroKey(h),'attack')};})()`);assert.equal(out.attack,.1);assert.equal(out.cleared,0);assert.equal(out.effects,0);
 out=json(r,`(()=>{const h=setupToken('guardian');const before=h.hp;h.hp=0;EmberwildTokenRuntime.afterDamage(h,foes[0],before,0);return {size:__EMBERWILD_TOKEN_TEST.combat.size,guard:effectTotal(heroKey(h),'guard')};})()`);assert.equal(out.size,0);assert.equal(out.guard,0);
 assert.deepEqual(r.errors,[]);
});
test('JSON changes affect equipped stats/abilities, deleted definitions retain owned snapshots and reload is stable',()=>{
 const r=game(),out=json(r,`(()=>{const h=partyMember(10),g=__EMBERWILD_TOKEN_TEST.makeToken('arcane',0);state.bag.push(g);equipCompanionToken(g.id,10);const cfg=exportableBalance();cfg.companions[0].initialStats.pierce=2;cfg.companions[0].growthPerLevel.pierce=.25;cfg.companionTokens.catalog.find(x=>x.id==='arcane').effects=[{key:'attackPct',value:10},{key:'flatAttack',value:2},{key:'hpPct',value:20},{key:'flatHp',value:3}];applyBalanceConfig(cfg);const changed=stats(h);const exported=exportableBalance();loadParty(packParty());const after=stats(partyMember(10));cfg.companionTokens.catalog=[];applyBalanceConfig(cfg);const retained=__EMBERWILD_TOKEN_TEST.item(partyMember(10)).snapshot;return {changed,after,retained,defs:exported.companionTokens.catalog.length};})()`);assert.deepEqual(out.changed,out.after);assert.equal(out.changed.pierce,2);assert.equal(out.defs,10);assert.equal(out.retained.id,'arcane');assert.deepEqual(r.errors,[]);
});
test('game and standalone editor share exact companion/token contracts',()=>{const html=fs.readFileSync(path.resolve(root,'../Emberwild-Balance/balance-editor.html'),'utf8');for(const [id,file] of [['companion-model-v1','js/character/companion-model.js'],['companion-token-model-v1','js/items/companion-token-model.js']]){const embedded=html.match(new RegExp('<script id="'+id+'">\\s*([\\s\\S]*?)</script>'))?.[1];assert.equal(embedded.trim(),fs.readFileSync(path.join(root,file),'utf8').trim());}});
test('sixteen player equipment/stat snapshots equal the pre-change d651f64 checkpoint',()=>{
 const r=loadRuntime(root);r.run('Math.random=()=>.5;start(0);');
 const out=json(r,`(()=>{const out=[];for(const job of [0,1,2,3])for(const lv of [1,15,30,60]){const h=initial(job);h.lv=lv;h.stats=[5,6,7];h.advanced=lv>=15;for(const slot of [1,2,3,3]){const g=gear(1,slot,2,job);g.plus=2;g.affix=[{type:0,value:2,rank:1}];h.bag.push(g);h.equipped.push(g.id);}out.push({job,lv,v:stats(h)});}return out;})()`);
 assert.deepEqual(out,JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/player-before-tokens.json'),'utf8')));
});
test('actual kill settlement drops one token and records one item with quality in both journals',()=>{
 const r=game(),out=json(r,`(()=>{const cfg=exportableBalance();cfg.companionTokens.drop.chanceByDifficulty=[1,1,1];cfg.companionTokens.drop.qualityWeights=[0,0,0,1];cfg.companionTokens.catalog=cfg.companionTokens.catalog.filter(x=>x.id==='arcane');applyBalanceConfig(cfg);closeModal();Math.random=()=>.5;spawnGroup();const e=foes[0];e.hp=0;rewardGroupKill(e);rewardGroupKill(e);const tokens=state.bag.filter(EmberwildTokens.isToken);return {tokens:tokens.map(g=>({name:g.snapshot.name,q:g.rar})),journal:[...expeditionLoot.items].filter(([name])=>name.includes('魔導信物')),battle:activeBattleStat.drops};})()`);
 assert.deepEqual(out.tokens,[{name:'魔導信物',q:3}]);assert.equal(out.journal.length,1);assert.equal(out.journal[0][1].count,1);assert.equal(out.journal[0][1].rar,3);assert.equal(Object.entries(out.battle).find(([name])=>name.includes('魔導信物'))[1],1);assert.deepEqual(r.errors,[]);
});
test('probability boundaries, live timed drop boost, ordinary RNG outcomes, combat clocks and enemy damage hooks',()=>{
 const r=game(),out=json(r,`(()=>{const cfg=exportableBalance(),h=partyMember(10);cfg.companionTokens.drop.chanceByDifficulty=[.01,.01,.01];cfg.companionTokens.catalog.find(x=>x.id==='guardian').ability.chance=.5;applyBalanceConfig(cfg);const g=__EMBERWILD_TOKEN_TEST.makeToken('guardian');state.bag.push(g);equipCompanionToken(g.id,10);Math.random=()=>.5;const boundary=__EMBERWILD_TOKEN_TEST.trigger(h,'receivedHit');Math.random=()=>.499;const below=__EMBERWILD_TOKEN_TEST.trigger(h,'receivedHit');partyClock+=1;const cooldown=__EMBERWILD_TOKEN_TEST.trigger(h,'receivedHit');partyClock+=1;const again=__EMBERWILD_TOKEN_TEST.trigger(h,'receivedHit');const e={id:'boost',lv:1,region:0,monsterId:'map0_mob0',kind:'normal',difficulty:0},noBoost=__EMBERWILD_TOKEN_TEST.rollTokens(e,()=>.015).length;party.timedBoosts=[{itemId:'test-drop',name:'掉寶測試',boostType:'drop',bonusPercent:100,durationMinutes:1,expiresAt:Date.now()+60000}];const boost=__EMBERWILD_TOKEN_TEST.rollTokens({...e,id:'boost2',__tokenDropRolled:false},()=>.015).length;resetEncounter();const end=__EMBERWILD_TOKEN_TEST.makeToken('endurance');state.bag.push(end);equipCompanionToken(end.id,10);party.active=[10];h.active=[null,null];h.procSlots=[null,null];h.supportSlots=[null,null];foes=[makeEnemy(0,h,()=>.5)];foes[0].hp=100000;foes[0].atk=1;running=false;for(const x of pacedRound()){}const paused=__EMBERWILD_TOKEN_TEST.combat.size;running=true;closeModal();const rounds=[];for(let n=0;n<7;n++){for(const x of pacedRound()){}rounds.push(effectTotal(heroKey(h),'attack'));}resetEncounter();equipCompanionToken(g.id,10);foes=[makeEnemy(0,h,()=>.5)];foes[0].atk=15;h.hp=stats(h).hp;Math.random=()=>.1;const before=h.hp;performEnemyBasic(foes[0]);const enemyHook=h.hp<before&&effectTotal(heroKey(h),'guard')===.1;return {boundary,below,cooldown,again,noBoost,boost,paused,rounds,enemyHook};})()`);
 assert.equal(out.boundary,false);assert(out.below);assert.equal(out.cooldown,false);assert(out.again);assert.equal(out.noBoost,0);assert.equal(out.boost,1);assert.equal(out.paused,0);assert.deepEqual(out.rounds,[0,0,0,.1,.1,.1,0]);assert(out.enemyHook);assert.deepEqual(r.errors,[]);
 const outcomes=[false,true].map(enabled=>{const g=game();return json(g,`(()=>{const d=exportableBalance();d.companionTokens.drop.enabled=${enabled};d.companionTokens.drop.chanceByDifficulty=[1,1,1];applyBalanceConfig(d);Math.random=()=>.5;const e=makeEnemy(0,playerHero(),()=>.5);const drops=rollConfiguredDrops(e,()=>0);return {drops:drops.map(x=>({rule:x.ruleId,type:x.type,quantity:x.quantity})),ordinary:pendingGearLoot.filter(x=>!EmberwildTokens.isToken(x)).map(x=>({tier:x.tier,plus:x.plus,affix:x.affix})),materials:state.materials};})()`);});assert.deepEqual(outcomes[0],outcomes[1]);
});
test('loading old token snapshots respects current HP cap; failed mutations roll back; invalid source references reject',()=>{
 const r=game(),out=json(r,`(()=>{const cfg=exportableBalance();cfg.companionTokens.catalog.find(x=>x.id==='arcane').effects=[{key:'flatHp',value:100}];applyBalanceConfig(cfg);const g=__EMBERWILD_TOKEN_TEST.makeToken('arcane',0);state.bag.push(g);equipCompanionToken(g.id,10);partyMember(10).hp=stats(partyMember(10)).hp;const old=packParty();cfg.companionTokens.catalog.find(x=>x.id==='arcane').effects=[{key:'flatHp',value:1}];applyBalanceConfig(cfg);loadParty(old);const h=partyMember(10),cap=stats(h).hp,hp=h.hp;const saveBase=save;save=()=>false;const unloaded=unequipCompanionToken(10),still=h.tokenId===g.id;const another=__EMBERWILD_TOKEN_TEST.makeToken('berserk');state.bag.push(another);const equipped=equipCompanionToken(another.id,10),rollback=h.tokenId===g.id&&h.hp===hp;save=saveBase;let rejected=false;cfg.companionTokens.drop.maps=[999];try{applyBalanceConfig(cfg);}catch{rejected=true;}return {cap,hp,unloaded,still,equipped,rollback,rejected};})()`);assert.equal(out.hp,out.cap);assert.equal(out.unloaded,false);assert(out.still);assert.equal(out.equipped,false);assert(out.rollback);assert(out.rejected);
});
test('real induced proc gets its token bonus once and failed healing casts do not consume trigger limits',()=>{
 const r=game(),out=json(r,`(()=>{const cfg=exportableBalance();const t=cfg.companionTokens.catalog.find(x=>x.id==='arcane');t.effects=[];t.ability.event='procSkill';cfg.classes[0].skills[0].tags=['induce'];cfg.classes[0].skills[0].induction={targets:[{kind:'procSlot',slot:0,chance:1}]};applyBalanceConfig(cfg);playerHero().lv=15;syncParty();const h=partyMember(10),g=__EMBERWILD_TOKEN_TEST.makeToken('arcane');state.bag.push(g);equipCompanionToken(g.id,10);party.active=[0,10];h.procSlots=[2,null];foes=[makeEnemy(0,h,()=>.5)];foes[0].hp=10000;Math.random=()=>.5;const cast=castPartySkill(h,0,battleStats(h)),used=__EMBERWILD_TOKEN_TEST.combat.get(10).used;resetEncounter();const prayer=__EMBERWILD_TOKEN_TEST.makeToken('prayer');state.bag.push(prayer);equipCompanionToken(prayer.id,13);const priest=partyMember(13);priest.skills[1]=0;const failed=castPartySkill(priest,1,battleStats(priest)),uses=__EMBERWILD_TOKEN_TEST.combat.get(13).used;return {cast,used,failed,uses};})()`);assert.notEqual(out.cast,false);assert.equal(out.used,1);assert.equal(out.failed,false);assert.equal(out.uses,0);assert.deepEqual(r.errors,[]);
});
