const assert=require('node:assert/strict');
const {loadRuntime}=require('./headless-runtime.cjs');
const fs=require('node:fs');
const path=require('node:path');
const test=require('node:test');
const root=path.resolve(__dirname,'..'),editorRoot=process.env.EMBERWILD_BALANCE_ROOT||path.resolve(root,'../Emberwild-Balance');
test('Real game/editor modules preserve elemental effects across combat, saves, reserve and offline time',{skip:!fs.existsSync(editorRoot+'/balance-editor.html')},()=>{
const plain=x=>JSON.parse(JSON.stringify(x));
const e=loadRuntime(editorRoot,'balance-editor.html');
const g=loadRuntime(root);g.run('selectSaveSlot(1);start(0);closeModal();running=false;state.gold=100000;Math.random=()=>.99;');
assert.deepEqual(plain(e.run('validateData()')),[]);
const ec=plain(e.run('__EMBERWILD_MASTERY_EDITOR.cleanExport()')),gc=plain(g.run('exportableBalance()'));
assert.deepEqual(ec.shopSettings,gc.shopSettings);
for(const id of ['ward_fire','elementTonic_fire'])assert.deepEqual(ec.items.find(x=>x.id===id),gc.items.find(x=>x.id===id));
e.run("selected.itemMode='element';selected.item=data.items.filter(x=>!EmberwildTimedBoosts.isItem(x)&&x.type!=='healPotion'&&x.id!=='power_tier_reroll').findIndex(x=>x.id==='ward_fire');renderItems();");
assert(e.elements.get('app').innerHTML.includes('效果強度（%）'));
assert(e.elements.get('app').innerHTML.includes('效果持續時間（現實分鐘）'));
assert.equal(e.run("flattenSettingLeaves(data.balanceSettings).some(([p])=>/^combat\\.supply\\.(wardResistance|elementTonicDamage)$/.test(p))"),false);
g.run("state.consumables.ward_fire=3;state.consumables.elementTonic_fire=3;state.consumables.imbue_fire=2;");
const before=plain(g.run('({gold:state.gold,ward:state.consumables.ward_fire,tonic:state.consumables.elementTonic_fire})'));
g.run("buySupply('ward_fire');buySupply('elementTonic_fire');party.market=generateMarket();party.market.offers.push({id:'1-99',kind:'item',key:'ward_fire',qty:1,price:10,sold:false,ruleId:'oldward'});buyMarketOffer('1-99');");
assert.deepEqual(plain(g.run('({gold:state.gold,ward:state.consumables.ward_fire,tonic:state.consumables.elementTonic_fire})')),before);
assert(!g.run('marketCards()').includes("buyMarketOffer('1-99')"));
e.run("Object.assign(data.items.find(x=>x.id==='ward_fire'),{effectPercent:40,durationMinutes:1.5,statEffects:{hp:50,attack:7}});Object.assign(data.items.find(x=>x.id==='elementTonic_fire'),{effectPercent:55,durationMinutes:2.25});");
const cfg=plain(e.run('__EMBERWILD_MASTERY_EDITOR.cleanExport()'));g.ctx.editedConfig=cfg;g.run('applyBalanceConfig(editedConfig);');
assert.deepEqual(plain(g.run("SHOP.find(x=>x.id==='ward_fire').statEffects")),{hp:50,attack:7});
for(const mutation of ["item.effectPercent=101","item.durationMinutes=0","item.durationMinutes=Infinity","item.duration=10"]){
  const result=g.run(`(()=>{const cfg=exportableBalance(),item=cfg.items.find(x=>x.id==='ward_fire'),before=JSON.stringify(exportableBalance());${mutation};try{applyBalanceConfig(cfg);return false;}catch{return JSON.stringify(exportableBalance())===before;}})()`);
  assert.equal(result,true,'Invalid potion config must not change live settings: '+mutation);
}
g.run("useSupply('ward_fire');useSupply('elementTonic_fire');useSupply('imbue_fire');");
const ward=plain(g.run('state.ward')),tonic=plain(g.run('state.elementTonic'));
assert.equal(ward.expiresAt,g.now+90000);assert.equal(tonic.expiresAt,g.now+135000);
assert.equal(ward.effectPercent,40);assert.equal(tonic.effectPercent,55);
assert.equal(g.run("supplyEffect(state,'ward','ice')"),0);
assert.equal(g.run("supplyEffect(state,'elementTonic','fire')"),.55);
assert(g.run('supplyStatus(state)').includes('現實時間'));
assert(g.run('battleBuffRows()').includes('40%'));
assert(g.run('battleBuffRows()').includes('55%'));
const hp=g.run('solo.stats(state).hp');
assert.equal(g.run("(()=>{const b=state.ward;state.ward=null;const v=solo.stats(state).hp;state.ward=b;return v;})()"),hp-50);
g.run("state.consumables.speed4_30m=1;useSupply('speed4_30m');");
const expiry=g.run('state.ward.expiresAt');
for(const rate of [1,2,4]){g.run(`setBattleSpeed(${rate});`);g.advance(1000);g.run('tick();');assert.equal(g.run('state.ward.expiresAt'),expiry);assert.equal(g.run('state.ward.expiresAt-Date.now()'),expiry-g.now);}
const saved=plain(g.run('packParty()'));
const validated=plain(g.run('validateParty(packParty())'));
assert.equal(validated.members[0].ward.expiresAt,ward.expiresAt);
assert.equal(validated.members[0].ward.effectPercent,40);
assert.deepEqual(validated.members[0].ward.statEffects,{hp:50,attack:7});
g.advance(10000);
g.run("useSupply('ward_fire')");assert.equal(g.run('state.ward.expiresAt'),g.now+90000);assert.equal(g.run('state.elementTonic.expiresAt'),tonic.expiresAt);
const failedBefore=plain(g.run('({buff:state.ward,count:state.consumables.ward_fire,hp:state.hp})'));
g.run("(()=>{const base=save;save=()=>false;try{useSupply('ward_fire');}finally{save=base;}})()");
assert.deepEqual(plain(g.run('({buff:state.ward,count:state.consumables.ward_fire,hp:state.hp})')),failedBefore);
const oldExpires=g.run('state.ward.expiresAt'),oldTurns=g.run('state.imbue.remainingTurns');
g.run("spawnGroup();foes.forEach(f=>{f.hp=f.maxhp=10000000;f.atk=1;});running=true;for(const _ of pacedRound()){}running=false;");
assert.equal(g.run('state.ward.expiresAt'),oldExpires);assert.equal(g.run('state.imbue.remainingTurns'),oldTurns-1);
const combat=plain(g.run(`(()=>{
 const h=state,enemy={...foes[0],id:'potion-target',hp:10000000,maxhp:10000000,atk:100,def:0,element:'fire',race:'beast',kind:'normal',lv:h.lv,turn:0,shield:0},read=()=>{enemy.hp=10000000;return resolveHit(enemy,10000,h,'fire',false);};
 const potion=h.elementTonic;h.elementTonic=null;const base=read();h.elementTonic=potion;const boosted=read();
 const readBasic=()=>{h.hp=10000;h.shield=0;enemy.turn=0;performEnemyBasic(enemy);return 10000-h.hp;};
 const ward=h.ward;h.ward=null;const basic=readBasic();h.ward=ward;const guardedBasic=readBasic();
 const sk={name:'測試火焰',effect:'damage',activation:'active',power:1,element:'fire',maxTargets:1,meta:{target:'enemy'}},readSkill=()=>{h.hp=10000;h.shield=0;castEnemySharedSkill(enemy,sk);return 10000-h.hp;};
 h.ward=null;const skill=readSkill();h.ward=ward;const guardedSkill=readSkill();
 withHero(h,clampVitals);return {base,boosted,basic,guardedBasic,skill,guardedSkill};
})()`));
assert.equal(combat.boosted,Math.round(combat.base*1.55));
assert.equal(combat.guardedBasic,Math.round(combat.basic*.6));
assert.equal(combat.guardedSkill,Math.round(combat.skill*.6));
g.run('running=false;state.hp=solo.stats(state).hp;party.active=[];');g.advance(95000);g.run('tick();');
assert.equal(g.run('state.ward'),null);assert.equal(g.run("activeSupply(state,'elementTonic')!==null"),true);assert.equal(g.run('state.hp'),hp-50);
g.advance(40000);g.run('tick()');assert.equal(g.run('state.elementTonic'),null);
g.ctx.oldSave=saved;g.run('oldSave.members[0].ward={element:"fire",remainingTurns:3,totalTurns:50,until:0,statEffects:{attack:7}};loadParty(oldSave);');
const migrated=g.run('state.ward.expiresAt');assert.equal(migrated,g.now+18000);assert.equal(g.run('state.ward.effectPercent'),40);
g.advance(5000);g.run('loadParty(packParty())');assert.equal(g.run('state.ward.expiresAt'),migrated);
const restart=loadRuntime(root,'index.html',Object.fromEntries(g.values),g.now+300000);
restart.run('continueFromTitle();');assert.equal(restart.run('state.ward'),null);assert.equal(restart.run('state.elementTonic'),null);assert.equal(restart.run("SHOP.find(x=>x.id==='ward_fire').effectPercent"),40);assert.equal(restart.run("SHOP.find(x=>x.id==='ward_fire').durationMinutes"),1.5);
for(const [scriptId,src] of [['timed-boost-schema-v1','js/items/timed-boosts.js'],['shop-catalog-v2','js/items/shop-catalog.js']]) {
 const embedded=fs.readFileSync(editorRoot+'/balance-editor.html','utf8').split('<script id="'+scriptId+'">\n')[1].split('\n</script>')[0];
 assert.equal(embedded,fs.readFileSync(root+'/'+src,'utf8'));
}
assert.deepEqual(g.errors,[]);assert.deepEqual(e.errors,[]);assert.deepEqual(restart.errors,[]);
});
