const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const {loadRuntime}=require('./headless-runtime.cjs'),root=path.resolve(__dirname,'..');
const json=(r,c)=>JSON.parse(r.run(`JSON.stringify(${c})`));
function game(job=0){const r=loadRuntime(root);r.run(`start(${job});closeModal();`);return r;}
test('A: initial class stays intact; new late team is blank; configurations and copies are independent',()=>{
 const r=game();const out=json(r,`(()=>{playerHero().lv=5;syncParty();save();allocate(0,3);const items=state.bag.map(g=>g.id);addTeamPlan();const blank=structuredClone(party.buildSystem.plans[1]);switchTeamPlan('team-2');const full={ap:playerHero().ap,sp:playerHero().sp};toggleBattle();const blocked=!running;changePlayerClass(1);learn(0);equipSkill(0,1);allocate(1,4);copyTeamPlan();switchTeamPlan('team-1');return {blank,full,blocked,currentJob:playerHero().job,stats:playerHero().stats,plans:party.buildSystem.plans,items,after:state.bag.map(g=>g.id)};})()`);
 assert.equal(out.blank.job,null);assert.deepEqual(out.blank.stats,[0,0,0]);for(const k of ['skills','supportLevels','companions','enlisted'])assert.deepEqual(out.blank[k],[]);assert(out.blank.equipped.every(x=>x===null));assert.equal(out.full.ap,12);assert.equal(out.full.sp,12);assert(out.blocked);assert.equal(out.currentJob,0);assert.deepEqual(out.stats,[3,0,0]);assert.equal(out.plans[1].job,1);assert.deepEqual(out.plans[1].stats,[0,4,0]);assert.deepEqual(out.plans[2].stats,[0,4,0]);assert.deepEqual(out.items,out.after);assert.deepEqual(r.errors,[]);
});
test('B: stable player identity and global class/element/weapon mastery survive free class changes and reload',()=>{
 const r=game(1),out=json(r,`(()=>{const key=memberKey(playerHero()),lv=playerHero().lv,xp=playerHero().xp,gold=state.gold;__EMBERWILD_MASTERY.gainMastery(playerHero(),'fire',27);changePlayerClass(0);__EMBERWILD_MASTERY.gainMastery(playerHero(),'sword',11);copyTeamPlan();changePlayerClass(3);changePlayerClass(1);const doc=packParty();loadParty(doc);return {key,afterKey:memberKey(playerHero()),lv,xp,gold,afterGold:state.gold,permanent:party.buildSystem.permanent,other:party.buildSystem.plans[1],skills:playerHero().skills};})()`);
 assert.equal(out.key,1);assert.equal(out.afterKey,1);assert.equal(out.gold,out.afterGold);assert.equal(out.permanent.classes[1].xp,27);assert.equal(out.permanent.classes[0].xp,11);assert.equal(out.permanent.classes[2].activated,false);assert.equal(out.permanent.classes[2].xp,0);assert.equal(out.permanent.masteries.fire,27);assert.equal(out.permanent.masteries.sword,11);assert.equal(out.other.job,0);assert(out.skills.every(x=>x===0));
});
test('C: real fire skill mastery threshold, one-time material unlock, team learning and reset remain separate',()=>{
 const r=game(1),out=json(r,`(()=>{const d=exportableBalance();d.classes[1].skills[2].requiredMasteryLevel=5;d.classes[1].skills[2].requiresAdvanced=true;d.classes[1].skills[2].learnCost=2;d.classes[1].skills[2].unlockConditions={classMasteryLevel:0,quests:[],materials:[{name:'測試徽章',quantity:1}]};applyBalanceConfig(d);playerHero().lv=15;syncParty();save();state.gold=1000;state.ore=50;state.materials['怨念碎片']=3;state.materials['測試徽章']=2;let xp=0;for(let i=0;i<5;i++)xp+=__EMBERWILD_MASTERY.masteryStepCost(i);playerHero().mastery.fire=xp-1;const before=unlockTeamSkill('core',2);playerHero().mastery.fire=xp;const noAdvance=unlockTeamSkill('core',2);advance();const ok=unlockTeamSkill('core',2),twice=unlockTeamSkill('core',2),material=state.materials['測試徽章'];learn(2);slotProcSkill(2,0);const a=structuredClone(__EMBERWILD_TEAMS.plan());copyTeamPlan();switchTeamPlan('team-2');resetSkills();const reset=structuredClone(__EMBERWILD_TEAMS.plan());switchTeamPlan('team-1');return {before,noAdvance,ok,twice,material,a,reset,fire:playerHero().mastery.fire,xp,perm:party.buildSystem.permanent,sp:playerHero().sp};})()`);
 assert.equal(out.before,false);assert.equal(out.noAdvance,false);assert(out.ok);assert(out.twice);assert.equal(out.material,1);assert.equal(out.a.skills[2],1);assert.equal(out.a.procSlots[0],2);assert(out.reset.skills.every(x=>x===0));assert.equal(out.perm.unlocks['1:core:2'],true);assert.equal(out.perm.payments['1:core:2'],true);assert.equal(out.fire,out.xp);assert.equal(out.sp,28); // total 32, original core/support + cost 2
});
test('D: real level rewards apply to all plans without overwriting allocations or repeat-load grants',()=>{
 const r=game(),out=json(r,`(()=>{copyTeamPlan();addTeamPlan();const gem=state.gems.slice();awardXP(need(1));allocate(0,2);const total=__EMBERWILD_TEAMS.budgets();switchTeamPlan('team-2');const second={ap:state.ap,sp:state.sp};switchTeamPlan('team-3');const blank={ap:state.ap,sp:state.sp};const raw=packParty();for(let i=0;i<3;i++)loadParty(raw);return {total,second,blank,plans:party.buildSystem.plans,gems:state.gems,gem,lv:playerHero().lv};})()`);
 assert.equal(out.lv,2);assert.deepEqual(out.total,{ap:3,sp:6});assert.deepEqual(out.second,{ap:3,sp:4});assert.deepEqual(out.blank,{ap:3,sp:6});assert.deepEqual(out.plans[0].stats,[2,0,0]);assert.deepEqual(out.gems,out.gem);
});
test('resets and class changes ask confirmation; cancel leaves every configuration unchanged',()=>{
 const r=game(),out=json(r,`(()=>{playerHero().lv=3;save();allocate(1,2);const before=JSON.stringify(packParty().buildSystem);let questions=0;confirm=()=>{questions++;return false};resetSkills();resetStats();changePlayerClass(1);return {questions,same:before===JSON.stringify(packParty().buildSystem)};})()`);assert.equal(out.questions,3);assert(out.same);
});
test('E: equipment references warn all teams; cancellation and force sale are atomic and grant once',()=>{
 const r=game(),out=json(r,`(()=>{copyTeamPlan();const id=state.equipped[0],gold=state.gold;let warning='';confirm=s=>{warning=s;return false};const cancelled=sellGear(id),kept=!!findGear(id);confirm=()=>true;const sold=sellGear(id);sellGear(id);return {cancelled,kept,sold,warning,delta:state.gold-gold,count:state.bag.length,slots:party.buildSystem.plans.map(p=>p.equipped[0])};})()`);assert.equal(out.cancelled,false);assert(out.kept);assert(out.sold);assert.match(out.warning,/隊伍 1.*隊伍 1 複本/);assert.equal(out.delta,12);assert.equal(out.count,4);assert.deepEqual(out.slots,[null,null]);
});
test('batch salvage uses the same reference warning, clears all plans, keeps locks and pending affixes',()=>{
 const r=game(),out=json(r,`(()=>{copyTeamPlan();const id=state.equipped[0];const g=findGear(id);g.locked=false;const locked=gear(1,0,0,0);locked.locked=true;state.bag.push(locked);const pending=gear(1,0,0,0);state.bag.push(pending);inlineAffixDrafts.set(affixDraftKey(pending),[]);let warning='';confirm=s=>{warning=s;return true};const ore=state.ore;__EMBERWILD_TEAM_EQUIPMENT.dispose([id,id,locked.id,pending.id],'salvage');return {warning,removed:!findGear(id),locked:!!findGear(locked.id),pending:!!findGear(pending.id),delta:state.ore-ore,refs:party.buildSystem.plans.map(p=>p.equipped[0])};})()`);assert.match(out.warning,/队伍|隊伍/);assert(out.removed&&out.locked&&out.pending);assert.equal(out.delta,3);assert.deepEqual(out.refs,[null,null]);
});
test('one physical token can differ by team; same-team duplicate ownership is rejected',()=>{
 const r=game(),out=json(r,`(()=>{recruitCompanion(10);recruitCompanion(12);const a=__EMBERWILD_TOKEN_TEST.makeToken('berserk'),b=__EMBERWILD_TOKEN_TEST.makeToken('arcane');state.bag.push(a,b);equipCompanionToken(a.id,10);copyTeamPlan();switchTeamPlan('team-2');unequipCompanionToken(10);const ok=equipCompanionToken(b.id,10),duplicate=equipCompanionToken(b.id,12);switchTeamPlan('team-1');const first=partyMember(10).tokenId;switchTeamPlan('team-2');const second=partyMember(10).tokenId;const count=state.bag.length;confirm=()=>true;sellGear(a.id);return {ok,duplicate,first,second,a:a.id,b:b.id,count,after:state.bag.length,cleared:party.buildSystem.plans[0].tokens[10]};})()`);assert(out.ok);assert.equal(out.duplicate,false);assert.equal(out.first,out.a);assert.equal(out.second,out.b);assert.equal(out.count,7);assert.equal(out.after,6);assert.equal(out.cleared,null);
});
test('gem instances are referenced when copying; changing or resetting releases each physical gem only once',()=>{
 const r=game(),out=json(r,`(()=>{state.gems[0]=2;socket(0,0);copyTeamPlan();switchTeamPlan('team-2');socket(0,-1);const afterOne=state.gems[0];switchTeamPlan('team-1');resetSkills();const final=state.gems[0];return {afterOne,final,instances:party.buildSystem.permanent.gemInstances,plans:party.buildSystem.plans.map(p=>p.sockets)};})()`);assert.equal(out.afterOne,1);assert.equal(out.final,2);assert.deepEqual(out.instances,{});assert(out.plans.every(p=>p.every(x=>x===null)));
});
test('F: running, paused encounters and between encounters block all configuration paths in core logic',()=>{
 const r=game(),out=json(r,`(()=>{copyTeamPlan();playerHero().lv=5;save();const before=JSON.stringify(packParty().buildSystem);const checks=[];for(const mode of ['running','paused','interval']){running=mode!=='paused';foes=mode==='interval'?[]:[{id:'enemy',hp:3}];const results=[switchTeamPlan('team-2'),changePlayerClass(1),learn(1),allocate(0,1),equipSkill(0,1),recruitCompanion(10),resetSkills()];checks.push(results.every(x=>x===false));}running=false;foes=[];return {checks,same:before===JSON.stringify(packParty().buildSystem)};})()`);assert(out.checks.every(Boolean));assert(out.same);
});
test('stop and safe switches reset all transient battle state while keeping permanent gains and item deadlines',()=>{
 const r=game(),out=json(r,`(()=>{recruitCompanion(10);copyTeamPlan();playerHero().hp=4;partyMember(10).hp=0;actorCooldowns={'0-0':8};supportCooldowns={'0-0':5};partyClock=22;nextActionAt=Date.now()+1000;state.imbue={element:'fire',until:Date.now()+60000};const deadline=state.imbue.until;running=true;foes=[{id:'test',hp:1}];stopTeamExploration();switchTeamPlan('team-2');const before={hp:playerHero().hp,max:stats(playerHero()).hp,dead:partyMember(10).hp,compMax:stats(partyMember(10)).hp,ac:actorCooldowns['0-0']||0,sc:supportCooldowns['0-0']||0,clock:partyClock,deadline:state.imbue.until};toggleBattle();return {before,deadline,afterAC:actorCooldowns['0-0']||0,afterSC:supportCooldowns['0-0']||0,clock:partyClock};})()`);assert.equal(out.before.hp,out.before.max);assert.equal(out.before.dead,out.before.compMax);assert.equal(out.before.ac,0);assert.equal(out.before.sc,0);assert.equal(out.before.clock,0);assert.equal(out.before.deadline,out.deadline);assert.equal(out.afterAC,0);assert.equal(out.afterSC,0);assert.equal(out.clock,0);
});
test('G: new saves, exact cold boot and repeated imports preserve every team, UID and permanent result',()=>{
 const r=game();r.run(`playerHero().lv=5;save();allocate(0,4);copyTeamPlan();switchTeamPlan('team-2');changePlayerClass(1);learn(0);renameTeamPlan('team-2','法術隊');__EMBERWILD_MASTERY.gainMastery(playerHero(),'fire',17);`);const raw=r.run('JSON.stringify(packParty())'),before=json(r,'party.buildSystem'),cold=loadRuntime(root,'index.html',{'emberwild-save-v1':raw});assert.deepEqual(json(cold,'party.buildSystem'),before);cold.run(`for(let i=0;i<3;i++)loadParty(packParty());`);assert.deepEqual(json(cold,'party.buildSystem'),before);assert.equal(cold.run('memberKey(playerHero())'),0);assert.deepEqual(cold.errors,[]);
});
test('legacy saves migrate learned skills into permanent unlocks and preserve allocations, mastery and inventory',()=>{
 const r=game(),out=json(r,`(()=>{playerHero().lv=5;save();allocate(0,3);__EMBERWILD_MASTERY.gainMastery(playerHero(),'sword',23);learn(1);equipSkill(1,1);const raw=structuredClone(packParty());delete raw.buildSystem;delete raw.members[0].playerId;const ids=raw.members.flatMap(h=>h.bag.map(g=>g.id));loadParty(raw);const first=structuredClone(packParty());loadParty(first);return {first:first.buildSystem,second:party.buildSystem,ids,after:state.bag.map(g=>g.id),stats:state.stats};})()`);assert.deepEqual(out.first,out.second);assert.deepEqual(out.ids,out.after);assert.deepEqual(out.stats,[3,0,0]);assert.equal(out.first.permanent.masteries.sword,23);assert.equal(out.first.permanent.unlocks['0:core:1'],true);
});
test('missing UID references become empty; corrupted allocations/slots/permanent records reject before live mutation',()=>{
 const r=game(),out=json(r,`(()=>{copyTeamPlan();const raw=structuredClone(packParty());raw.members[0].equipped[0]='missing';raw.buildSystem.plans[0].equipped[0]='missing';raw.buildSystem.plans[1].equipped[0]='missing';loadParty(raw);const cleaned=party.buildSystem.plans.every(p=>p.equipped[0]===null),saved=structuredClone(packParty()),live=party;let rejected=0;for(const change of [d=>d.buildSystem.plans[0].stats[0]=999,d=>d.buildSystem.plans[0].active=[0,0],d=>d.buildSystem.permanent.classes[2].xp=8,d=>d.buildSystem.permanent.playerKey=12]){const d=structuredClone(saved);change(d);try{loadParty(d)}catch{rejected++}}return {cleaned,rejected,same:party===live};})()`);assert(out.cleaned);assert.equal(out.rejected,4);assert(out.same);
});
test('failed saves roll back class switching, configuration resets, material unlock and referenced item disposal',()=>{
 const r=game(),out=json(r,`(()=>{copyTeamPlan();const before=JSON.stringify(packParty()),id=state.equipped[0];save=()=>false;const switched=switchTeamPlan('team-2'),changed=changePlayerClass(1),reset=resetSkills(),sold=sellGear(id);return {switched,changed,reset,sold,kept:!!findGear(id),before:JSON.parse(before),after:JSON.parse(JSON.stringify(packParty()))};})()`);for(const k of ['switched','changed','reset','sold'])assert.equal(out[k],false);assert(out.kept);assert.deepEqual(out.after,out.before);
});
test('real sword basic attacks and fire casts feed the existing XP rules into only the active player class',()=>{
 const r=game(),out=json(r,`(()=>{Math.random=()=>.5;spawnGroup();foes.forEach(e=>e.hp=e.maxhp=10000);performHeroBasic(playerHero());const sword=party.buildSystem.permanent.classes[0].xp;stopTeamExploration();changePlayerClass(1);const weapon=gear(1,0,0,1);state.bag.push(weapon);equipSharedGear(weapon.id,memberKey(playerHero()),0);learn(0);spawnGroup();foes.forEach(e=>e.hp=e.maxhp=10000);const cast=castPartySkill(playerHero(),0,battleStats(playerHero()));return {cast,sword,classes:party.buildSystem.permanent.classes,masteries:party.buildSystem.permanent.masteries};})()`);assert.notEqual(out.cast,false);assert.equal(out.sword,1);assert.equal(out.classes[0].xp,1);assert.equal(out.classes[1].xp,2);assert.equal(out.classes[2].xp,0);assert.equal(out.masteries.sword,1);assert.equal(out.masteries.fire,2);
});
test('class advancement is permanent and its existing cost is paid once; revisiting does not charge or reset mastery',()=>{
 const r=game(),out=json(r,`(()=>{playerHero().lv=15;save();__EMBERWILD_MASTERY.gainMastery(playerHero(),'sword',200);state.gold=5000;state.ore=100;state.materials['怨念碎片']=10;const before=state.gold;advance();const first=state.gold;changePlayerClass(1);changePlayerClass(0);advance();return {before,first,after:state.gold,advanced:state.advanced,permanent:party.buildSystem.permanent.classes[0],ore:state.ore,material:state.materials['怨念碎片']};})()`);assert.equal(out.before-out.first,500);assert.equal(out.after,out.first);assert(out.advanced);assert(out.permanent.advanced);assert.equal(out.permanent.xp,200);assert.equal(out.ore,80);assert.equal(out.material,7);
});
test('supported v1 and v2 single-hero saves use the same idempotent migration as version 3',()=>{
 for(const version of [1,2]){const r=game(),out=json(r,`(()=>{playerHero().lv=5;save();allocate(0,3);const raw=structuredClone(packParty().members[0]);raw.version=${version};delete raw.playerId;const ids=raw.bag.map(g=>g.id),lv=raw.lv,xp=raw.xp;loadParty(raw);const first=structuredClone(packParty());loadParty(first);return {first:first.buildSystem,second:party.buildSystem,ids,after:state.bag.map(g=>g.id),lv,xp,level:playerHero().lv,exp:playerHero().xp,stats:playerHero().stats};})()`);assert.deepEqual(out.first,out.second);assert.deepEqual(out.ids,out.after);assert.equal(out.level,out.lv);assert.equal(out.exp,out.xp);assert.deepEqual(out.stats,[3,0,0]);}
});
test('old all-companion formations preserve their three active members across migration and copies',()=>{
 const r=game(),out=json(r,`(()=>{for(const id of [10,11,12])recruitCompanion(id);party.active=[10,11,12];const raw=structuredClone(packParty());delete raw.buildSystem;loadParty(raw);copyTeamPlan();switchTeamPlan('team-2');loadParty(packParty());return {active:party.active,plan:__EMBERWILD_TEAMS.plan(),valid:__EMBERWILD_TEAMS.valid()};})()`);assert.deepEqual(out.active,[10,11,12]);assert.equal(out.plan.playerActive,false);assert(out.valid);
});
test('material unlock failure and ordinary allocation failure refund resources and leave the live configuration intact',()=>{
 const r=game(),out=json(r,`(()=>{const d=exportableBalance();d.classes[0].skills[1].requiredMastery=null;d.classes[0].skills[1].requiredMasteryLevel=0;d.classes[0].skills[1].unlockConditions={classMasteryLevel:0,quests:['tutorial'],materials:[{name:'鍛鐵',quantity:2}]};applyBalanceConfig(d);playerHero().lv=5;playerHero().tutorial=3;save();const before=structuredClone(packParty());save=()=>false;const unlock=unlockTeamSkill('core',1),allocated=allocate(0,2);return {unlock,allocated,before,after:JSON.parse(JSON.stringify(packParty()))};})()`);assert.equal(out.unlock,false);assert.equal(out.allocated,false);assert.deepEqual(out.after,out.before);
});
test('plan limits retain existing plans; blank plans round-trip and never contain battle-resource snapshots',()=>{
 const r=game(),out=json(r,`(()=>{for(let i=0;i<5;i++)addTeamPlan();const limit=addTeamPlan();switchTeamPlan('team-6');const d=exportableBalance();d.teamSettings.maxPlans=3;applyBalanceConfig(d);const raw=structuredClone(packParty());raw.buildSystem.plans[0].hp=9999;raw.buildSystem.plans[0].actorCooldowns={};loadParty(raw);return {limit,plans:party.buildSystem.plans,job:__EMBERWILD_TEAMS.plan().job,count:party.buildSystem.plans.length,keys:Object.keys(party.buildSystem.plans[0])};})()`);assert.equal(out.limit,false);assert.equal(out.count,6);assert.equal(out.job,null);assert(!out.keys.includes('hp'));assert(!out.keys.includes('actorCooldowns'));
});
test('balance edits check every plan before mutation, expand new skill arrays, and roll back a failed save',()=>{
 const r=game(),out=json(r,`(()=>{
  playerHero().lv=5;save();allocate(0,9);copyTeamPlan();resetStats();
  const settings=exportableBalance(),before=structuredClone(packParty());let rejected=0;
  for(const edit of [d=>d.balanceSettings.progression.levelRewards.abilityPoints=0,d=>d.classes[0].skills[0].learnCost=1000]){const d=structuredClone(settings);edit(d);try{applyBalanceConfig(d)}catch{rejected++}}
  const kept=JSON.stringify(exportableBalance())===JSON.stringify(settings),afterRejected=structuredClone(packParty());
  const added=structuredClone(settings),sk=structuredClone(added.classes[0].skills[0]);sk.id='job0-skill6';sk.name='測試新增技能';added.classes[0].skills.push(sk);applyBalanceConfig(added);
  const lengths=party.buildSystem.plans.map(p=>p.skills.length);loadParty(packParty());
  playerHero().hp=4;playerHero().shield=3;actorCooldowns={'0-0':8};save();
  const stable=structuredClone(packParty()),rules=exportableBalance(),cache=localStorage.getItem(BALANCE_KEY);save=()=>false;
  const d=structuredClone(rules);d.teamSettings.maxPlans=4;let failed=false;try{applyBalanceConfig(d)}catch{failed=true}
  return {rejected,kept,before,afterRejected,lengths,originalLength:settings.classes[0].skills.length,failed,stable,after:packParty(),rules,afterRules:exportableBalance(),cache,saved:localStorage.getItem(BALANCE_KEY),cd:actorCooldowns['0-0']};
 })()`);
 assert.equal(out.rejected,2);assert(out.kept);assert.deepEqual(out.afterRejected,out.before);assert.deepEqual(out.lengths,[out.originalLength+1,out.originalLength+1]);assert(out.failed);assert.deepEqual(out.after,out.stable);assert.deepEqual(out.afterRules,out.rules);assert.equal(out.saved,out.cache);assert.equal(out.cd,8);
});
